services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    image: pianofi-backend:dev
    ports:
      - "8000:8000"
    env_file:
      - packages/pianofi_config/.env
    volumes:
      - ./uploads:/app/uploads
      # - ./backend/app:/app/app
      - ./project-aws:/root/.aws
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /app/app
        - action: rebuild
          path: ./Dockerfile.dev
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: pianofi-frontend:dev
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.local
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000  # ✅ Use service name
    volumes:
      # - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
<<<<<<< HEAD:docker-compose-dev.yaml
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
=======
      - /app/.next
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./frontend/Dockerfile.dev
>>>>>>> 1945ec37d4516b4af2f119a4938f37cc11293fe4:docker-compose.yaml
    depends_on:
      - backend
  worker:
    build:
      context: .
      dockerfile: workers/Dockerfile
    image: pianofi-worker:dev
    env_file:
      - packages/pianofi_config/.env
    volumes:
      - ./uploads:/app/uploads     # host:container
      - ./workers:/app/workers
      - ./project-aws:/home/picogen2/.aws
    develop:
      watch:
        - path: ./workers
          target: /app/workers
          action: sync
    # entrypoint: ""
    # command: tail -f /dev/null
    restart: unless-stopped
    # needs gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]