[project]
name = "pianofi"
version = "0.1.0"
description = "AI-powered piano transcription and sheet music generation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "midi2audio>=0.1.1",
    "music21>=9.1.0",
]
